FROM php:fpm
RUN apt-get update && apt-get install -y \
      imagemagick \
      libfreetype6-dev \
      libjpeg62-turbo-dev \
      libmcrypt-dev \
      libpng12-dev \
      libmemcached-dev \
      vim \
      rsyslog \
    && docker-php-ext-install -j$(nproc) \
      exif \
      gd \
      iconv \
      mbstring \
      mcrypt \
      mysqli \
      pdo \
      pdo_mysql \
      opcache \
    && pecl install \
      igbinary \
      memcached \
      xdebug \
#      zip \
    && docker-php-ext-enable \
      igbinary \
      memcached \
      xdebug \
#      zip
    # Install Composer (NOT IN PRODUCTION!)
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \

# Install drush 8 for Drupal 8.
RUN composer global require drush/drush::8.x \
    && ln -s /root/.composer/vendor/drush/drush /usr/bin/drush
ENV PATH="/root/.composer/vendor/drush/drush:${PATH}"

#
# @TODO
#    Add config files for OPCache, other extensions.
#
#
#  Possible PHP extensions:
#
#   - OPCache
#   - Pear
#   - Curl
#   - php-pear
#   - php5-cli
#   - php5-common
#   - php5-curl
#   - php5-dev
#   - php5-imap
#   - php5-intl
#   - php5-json
#   - php5-ldap
#   - php5-mhash
#   - php5-mysqlnd
#   - php5-pspell
#   - php5-recode
#   - php5-redis
#   - php5-xdebug
#   - php5-xhprof
#   - php5-xmlrpc
#   - php5-xsl
#   - libgv-php5
#   - Opcache web viewer
